### ISSUE TITLE
DataService not working in iOS

### ISSUE THREAD

**Issue by happyesthete** [ccoenraets/forcejs#20]
I integrated an ionic 2 app with salesforce apis using force 2, which works fine in browser. But, I am unable to get it working on iOS. DataService instance in not returning any data and is always coming undefined. Even I am facing same issue in https://github.com/dreamhouseapp/dreamhouse-mobile-app. Again, all the apis are working fine in browser. Authentication Service is successfully returning authentication object, but data service is giving error. It stuck after successful authentication in app via mobile sdk. Please help me with this.

**Comment by cdhenao** [comment]
I'm facing the same issue with an iOS app. It's working fine in browser but when I try to run it on an iPad it returns me that can't find variable 'computeEndPointIfMissing'. This problem happens when I try to use some method from DataService and the appId is always undefined.

**Comment by happyesthete** [comment]
@cdhenao I fixed this issue. Check if this is helpful for you.
https://github.com/ccoenraets/forcejs/pull/21

**Comment by cdhenao** [comment]
Worked for me too, thank you so much! @happyesthete

**Comment by mao32** [comment]
Hi, me too have the same issue. The @happyesthete solution seems to work, if is it ok please pull his request in order to dist it

**Comment by mao32** [comment]
I found out an issue using create method on iOS.
Actually in android i can't see the salesforce login page

**Comment by happyesthete** [comment]
@mao32 My current fix don't cover these issues and I am sure not the cause for these issues, but I can fix these if you can give more detail.

**Comment by mao32** [comment]
@happyesthete If i try to call create method from iOS platform  it fails, instead it works on web browser, everything was ok with MobileSDK 4.3

**Comment by happyesthete** [comment]
Did you try dreamhouse app? You can have a look https://github.com/dreamhouseapp/dreamhouse-mobile-app
App will works fine with MobileSDK 5, and with my fix, and have a sample workflow integrated. I am able to complete one cordova app using the fix in my pull request. I only tested for ios. Also, make sure you are using cordova ios 4.3.0 when adding platform as latest 4.3.1 is not compatible.

**Comment by happyesthete** [comment]
This has been already fixed, so closing the issue.

**Comment by vivekweb** [comment]
@happyesthete i have created an apex api to use in Ionic app via forcejs. 
target is like '/API_URL_MAPPING_NAME/?QUERY_STRING'
above request is working fine in android and not in iOS. so i tried to debug from salesforce and found no parameters are received when requested from iOS.

i am using latest forcejs (2.0.5) and please refer the ionic environment below
<img width="449" alt="screen shot 2017-09-04 at 6 15 13 pm" src="https://user-images.githubusercontent.com/17842048/30024155-0ded5738-91a5-11e7-93e3-84143b10ac4f.png">

And i am getting error in iOS while using create() service. also noticed in log that instead of posting as json data, they are appended to target url and getting "The operation couldn’t be completed. (SALESFORCE_DOMAIN/services/data/v36.0/sobjects/Task?Description__c=test%20task%20from%20home%20screen&Status__c=Open)" error

Please help to fix this issue

**Comment by happyesthete** [comment]
@vivekweb I will suggest you to first check this dreamhouse app with latest version of forcejs and make sure it is working fine in ios https://github.com/dreamhouseapp/dreamhouse-mobile-app. Then maybe you can refer the configuration from that app, if that is working. Also, keep in mind sometimes latest version of ios sdk is not working. So, give fixed build number in package.json

Also, few hints, might be old as not worked with this plugin recently, but still can be relevant (please double check on this):

1) `cordova platform add ios@4.3.0`

as latest ios sdk was not working for me at that time (not sure whether fixed in latest version).

2) 
`cordova plugin remove com.salesforce
cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin --force`

**Comment by vivekweb** [comment]
@happyesthete sorry for late reply. i did setup environment with current mobilesdk plugin (5.2) and it requires ios (4.4.0). still i am getting same error message. also tried changing "create()" to "request()" response is same. I am not clear how data passed to those methods are being changed to GET instead of POST.

**Comment by vivekweb** [comment]
@happyesthete i had some conflicts in latest mobilesdk plugin & ios platform, i fixed them. now i can able to succeed in create() and request(). initially i thought, there might be some issues in forcejs module. in mobilesdk 5.2, they fixed issues for com.salesforce.network related on iOS.
thanks for sharing your comments

**Comment by happyesthete** [comment]
Good job, glad to hear you its working for you.
